### ISSUE TITLE
How Scene2DScreen is used?

### ISSUE THREAD

**Issue by firestorm23** [danirod/jumpdontdie#2]
You have `Scene2DScreen` in `es.danirod.jddprototype.scene2d` package but it seem not being used anywhere, yet it uses instances of classes `SpikeActor` and `PlayerActor`. Is it used somewhere or not ? Or it is used in some other implementation of game logic, is it?

**Comment by danirod** [comment]
Yeah, it is only used in other implementations of game logic that are covered in the tutorial before I start developing the actual prototype. This is the case of the `.scene2d` package and the `.box2d` package. That code is kept as a reference file for anyone interested in the code for those lessons and on how Scene2D or Box2D works. This is explained in the readme file.
