### ISSUE TITLE
Incrementar versionSdk

### ISSUE THREAD

**Issue by danirod** [danirod/jumpdontdie#3]
Google Play informa por email que [en noviembre las actualizaciones a apps de la Google Play Store deben tener lo menos el targetSdkVersion configurado a 26][1] y que el paquete es.danirod.jddprototype.android está afectado por tener el targetSdkVersion a 22.

Como no parece retroactivo y no parece que vayan a penalizar a las aplicaciones que ya estén cargadas, por ahora voy a pasar, pero abro este ticket por si tengo que recordar esto más adelante.

[1]: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by danirod** [comment]
Abrir un pull request es gratis.

**Comment by cinnamon17** [comment]
Hombre ya tengo el codigo arreglado pero no puedo hacer pull request

**Comment by cinnamon17** [comment]
crea otro branch

**Comment by cinnamon17** [comment]
Listo ya esta actualizado

**Comment by danirod** [comment]
Genial, le intentaré echar un ojo a lo largo del fin de semana y si hago un merge, marco el issue como completado.

¡Muchas gracias y bienvenido al open source!

**Comment by danirod** [comment]
Corregido en ace415ed4b49e5d005819c8da11556c2c6a3bfd8.
